app/models/customer.rb, app/models/invoice.rb, app/models/item.rb, app/models/merchant.rb
-added relationships in models
=> creating relationships in models

app/controllers/api/v1/invoice_items_contoller.rb, app/controllers/api/v1/invoices_controller.rb, app/controllers/api/v1/items_controller.rb, app/models/merchant.rb, config/routes.rb, spec/factories/invoice_items.rb, spec/factories/invoices.rb, spec/factories/items.rb, spec/requests/api/v1/invoice_items_request_spec.rb, spec/requests/api/v1/invoice_request_spec.rb, spec/requests/api/v1/items_request_spec.rb
-Worked on Person B endpoints of invoices, items, invoice_items 
-Need to review invoice_items_request_spec.rb test 
-Added a has many relationships for merchants
=> Person b part 1

app/controllers/api/v1/invoice_items_controller.rb, spec/requests/api/v1/invoice_items_request_spec.rb, spec/requests/api/v1/invoice_request_spec.rb, spec/requests/api/v1/items_request_spec.rb
=> /invoice_items/:id test

app/controllers/api/v1/invoices/transactions_controller.rb, config/routes.rb, spec/factories/invoices.rb, spec/requests/api/v1/invoices/transactions_request_spec.rb
Adds route for invoice relationship endpoint: transaction
=> Add invoice transaction relationship

config/routes.rb
Added new namespaced routes for relationship endpoints. Merge when ready! 💯
=> Add routes for all relationship endpoints

Gemfile, Gemfile.lock, app/controllers/api/v1/merchants/invoices_controller.rb, app/controllers/api/v1/merchants/items_controller.rb, app/serializers/customer_serializer.rb, app/serializers/invoice_item_serializer.rb, app/serializers/invoice_serializer.rb, app/serializers/item_serializer.rb, app/serializers/merchant_serializer.rb, app/serializers/transacation_serializer.rb, spec/requests/api/v1/invoices/transactions_request_spec.rb, spec/requests/api/v1/merchants/invoices_request_spec.rb, spec/requests/api/v1/merchants/items_request_spec.rb
-added active_model_serializers gem and folders to exclude created_at and updated_at 
-added relationship endpoint tests for merchants
=> Merchants relationship

app/controllers/api/v1/invoices/customer_controller.rb, app/controllers/api/v1/invoices/invoice_items_controller.rb, app/controllers/api/v1/invoices/items_controller.rb, app/controllers/api/v1/invoices/merchant_controller.rb, spec/requests/api/v1/invoices/customer_request_spec.rb, spec/requests/api/v1/invoices/invoice_items_request_spec.rb, spec/requests/api/v1/invoices/items_request_spec.rb, spec/requests/api/v1/invoices/merchant_request_spec.rb, spec/requests/api/v1/invoices/transactions_request_spec.rb
Completes invoice relationship endpoints, merge when ready!
=> Invoice relationships

app/controllers/api/v1/items/invoice_items_controller.rb, app/controllers/api/v1/items/merchant_controller.rb, spec/requests/api/v1/items/invoice_items_request_spec.rb, spec/requests/api/v1/items/merchant_request_spec.rb
Completes relationship endpoints for items
=> Items relationships

app/controllers/api/v1/invoice_items/invoice_controller.rb, app/controllers/api/v1/invoice_items/item_controller.rb, config/routes.rb, spec/requests/api/v1/invoice_items/invoice_request_spec.rb, spec/requests/api/v1/invoice_items/item_request_spec.rb
Completes relationship endpoints for index items
=> Invoice items relationships

app/controllers/api/v1/customers/invoices_controller.rb, app/controllers/api/v1/customers/transactions_controller.rb, app/controllers/api/v1/transactions/invoice_controller.rb, app/models/customer.rb, app/serializers/transacation_serializer.rb, app/serializers/transaction_serializer.rb, config/routes.rb, db/migrate/20161129215751_change_colume_in_transaction.rb, db/schema.rb, spec/requests/api/v1/customers/invoices_request_spec.rb, spec/requests/api/v1/customers/transactions_request_spec.rb, spec/requests/api/v1/transactions/invoice_request_spec.rb
-added endpoints customers 
-changed credit card column to string
=> Transactions and customers

app/controllers/api/v1/merchants/find_controller.rb, config/routes.rb, spec/requests/api/v1/merchants/find_request_spec.rb
-created a single finder for merchant
=> find controller for merchants

app/controllers/api/v1/items/find_controller.rb, config/routes.rb, spec/requests/api/v1/items/find_request_spec.rb
-added single finder for items
=> single finder for items

app/controllers/api/v1/customers/find_controller.rb, app/controllers/api/v1/invoices/find_controller.rb, config/routes.rb, spec/requests/api/v1/customers/find_request_spec.rb, spec/requests/api/v1/invoices/find_request_spec.rb
Completes find and find_all query params for invoice and customer.
=> Find invoice customer

app/controllers/api/v1/invoice_items/find_controller.rb, app/controllers/api/v1/items/find_controller.rb, app/controllers/api/v1/merchants/find_controller.rb, app/controllers/api/v1/transactions/find_controller.rb, config/routes.rb, spec/requests/api/v1/invoice_items/find_request_spec.rb, spec/requests/api/v1/items/find_request_spec.rb, spec/requests/api/v1/merchants/find_request_spec.rb, spec/requests/api/v1/transactions/find_request_spec.rb
-find and find_all routes/tests/controllers for transactions, invoice_items, merchants and items
=> Find find all

app/serializers/invoice_item_serializer.rb, app/serializers/item_serializer.rb
=> changing unit price to $

app/controllers/api/v1/merchants/most_revenue_controller.rb, config/routes.rb, db/migrate/20161130194636_changecolumnnameinitems.rb, db/migrate/20161130195025_changecolumnnameinitems_invoices.rb, db/schema.rb
=> changing column name

app/controllers/api/v1/merchants/revenue_controller.rb, app/models/merchant.rb, app/serializers/revenue_serializer.rb, config/routes.rb, spec/requests/api/v1/merchants/revenue_request_spec.rb
Adds revenue for merchant, works now!
=> Add revenue for merchant

app/controllers/api/v1/merchants/revenue_controller.rb, app/models/invoice.rb, app/models/merchant.rb, app/models/transaction.rb, app/serializers/revenue_serializer.rb, spec/requests/api/v1/merchants/revenue_request_spec.rb
Merchant revenue by date complete!
=> Merchant revenue

app/controllers/api/v1/customers/favorite_merchant_controller.rb, app/controllers/api/v1/merchants/favorite_customer_controller.rb, app/controllers/api/v1/merchants/most_revenue_controller.rb, app/models/customer.rb, app/models/merchant.rb, config/routes.rb
-favorite merchant for customer 
-favorite customer for merchant
=> Business intel 2

app/controllers/api/v1/items/best_day_controller.rb, app/serializers/best_day_serializer.rb, config/routes.rb
=> business intel best_day

app/controllers/api/v1/invoice_items/find_controller.rb, app/controllers/api/v1/items/best_day_controller.rb, app/controllers/api/v1/items/find_controller.rb, app/models/invoice_item.rb, app/models/item.rb
-fixed all unit_price errors(we should be down to only 6 failures now) 
-I put together a quick way to get rid of the error but will need to refactor the code out to a model
=> fixed unit price error

app/controllers/api/v1/items/most_items_controller.rb, app/models/item.rb, config/routes.rb, spec/requests/api/v1/items/most_items_request_spec.rb
Got Top items by total number sold business logic working! 5 failures remaining on test harness, merge when ready!
=> Finish items ranked by number of items sold

spec/models/customer_spec.rb, spec/models/invoice_item_spec.rb, spec/models/invoice_spec.rb, spec/models/item_spec.rb, spec/models/merchant_spec.rb, spec/models/transaction_spec.rb
-added model tests relationships for customers, merchants, transactions, invoices, invoice_items, items
=> Model tests

app/controllers/api/v1/merchants/revenue_controller.rb, app/models/merchant.rb, app/serializers/total_revenue_serializer.rb, config/routes.rb, spec/requests/api/v1/merchants/total_revenue_request_spec.rb
Completes total revenue for date, passing test harness
=> Complete total revenue for date

app/controllers/api/v1/merchants/most_revenue_controller.rb, app/models/merchant.rb
-most_revenue by quantity business intel
=> Business intel 4

app/controllers/api/v1/items/most_revenue_controller.rb, app/models/item.rb, config/routes.rb, spec/requests/api/v1/items/most_revenue_spec.rb, spec/requests/api/v1/merchants/total_revenue_request_spec.rb
Two failures on test harness! Merge when ready! 👍
=> Complete top items by total revenue, test for merchants total revenue

app/controllers/api/v1/items/best_day_controller.rb, app/models/item.rb
-best day for items business logic
=> business logic for items best_day

app/controllers/api/v1/customers/favorite_merchant_controller.rb, app/controllers/api/v1/invoice_items/find_controller.rb, app/controllers/api/v1/invoice_items/invoice_controller.rb, app/controllers/api/v1/invoice_items_controller.rb, app/controllers/api/v1/invoices_controller.rb, app/controllers/api/v1/items/find_controller.rb, app/controllers/api/v1/items_controller.rb, app/controllers/api/v1/merchants/favorite_customer_controller.rb, app/controllers/api/v1/merchants/find_controller.rb, app/controllers/api/v1/merchants/invoices_controller.rb, app/controllers/api/v1/merchants/items_controller.rb, app/controllers/api/v1/merchants/most_revenue_controller.rb, app/controllers/api/v1/merchants/revenue_controller.rb, app/controllers/api/v1/transactions/find_controller.rb, app/controllers/api/v1/transactions/invoice_controller.rb, app/models/merchant.rb, coverage/.resultset.json, coverage/index.html, spec/models/invoice_spec.rb, spec/models/transaction_spec.rb
Fixed a couple of tests, deleted white space, etc
=> Clean up code, a few minor fixes

README.md, app/models/invoice.rb, app/models/merchant.rb, spec/models/invoice_spec.rb, spec/models/merchant_spec.rb, spec/requests/api/v1/customers/favorite_merchant_request_spec.rb, spec/requests/api/v1/merchants/favorite_customer_request_spec.rb, spec/requests/api/v1/merchants/revenue_request_spec.rb
-model tests for merchant methods
=> More tests

spec/requests/api/v1/invoice_items/find_request_spec.rb, spec/requests/api/v1/items/find_request_spec.rb
Added tests on finders for item and invoice item, the test coverage is a lot higher now! Merge when you get a chance.
=> Complete tests
